### ISSUE TITLE
Introduce gopkg support

### ISSUE THREAD

**Issue by Dynom** [renstrom/fuzzysearch#11]
Hi,

I'm planning of using your library, but in order to have no future build-issues, I would like to pin versions to avoid the obvious problems. Would you mind creating branches/tags for your releases? The (simple) instructions are on: https://labix.org/gopkg.in

Cheers,

Mark

**Comment by renstrom** [comment]
Sure thing. I added a `v1.0.0` tag.

    go get gopkg.in/renstrom/fuzzysearch.v1/...

**Comment by Dynom** [comment]
Excellent, thanks!
