### ISSUE TITLE
Case insensetivity

### ISSUE THREAD

**Issue by rharriso** [renstrom/fuzzysearch#8]
@renstrom , I'd like to add some facility for case insensitivity would that be find with you?

**Comment by renstrom** [comment]
Sounds like a good idea. I'm thinking they would have `Fold` as function suffix to align with [`strings.EqualFold`](http://golang.org/pkg/strings/#EqualFold) in the standard library.

**Comment by rharriso** [comment]
That makes a lot of sense.

Right now I'm looking to improve the performance of the Rank find function.... I didn't expect you to get back to me so soon.

I'll open a PR for the performance, and then move on to a Fold after you review.

**Comment by renstrom** [comment]
>I didn't expect you to get back to me so soon.

Heh, well you caught my attention while brushing my teeth.

>Right now I'm looking to improve the performance of the Rank find function

Cool, looking forward to see the result :) Might as well add a `BenchmarkRankFind()` to `fuzzy_test.go` while you're at it (and include before/after results).

**Comment by rharriso** [comment]
cool cool, Hopefully I'll get back to you by tommorow

**Comment by renstrom** [comment]
No worries, take your time!

**Comment by renstrom** [comment]
By the way, wouldn't this just be a matter of using `strings.ToLower()` on the arguments to `Match()`? Basically:

```go
fuzzy.Match(strings.ToLower(source), strings.ToLower(target))
```

**Comment by rharriso** [comment]
Could, yes, but it I've had trouble with tolower being much slower than
fold in one of my applications. Might be an artifact of the specific inputs
however.

**Comment by renstrom** [comment]
Just thought I'd mention it, but you're probably right!

**Comment by renstrom** [comment]
@rharriso any update? :)

**Comment by rharriso** [comment]
I've been in the process of moving (Sorry I didn't let you know). I'll be
able to work on this starting next week.

**Comment by renstrom** [comment]
Don't worry about it, I was just checking in. No rush!

**Comment by rharriso** [comment]
Here's what I got so far: https://github.com/renstrom/fuzzysearch/compare/master...rharriso:feature/case-insensetive?expand=1

Still need to do levenstein distance.

I tried passing in a function instead of a boolean flag, but the benchmarks for long text doubled and  went up 25% for short text

**Comment by renstrom** [comment]
So I was curious and and took it for a spin (https://github.com/renstrom/fuzzysearch/commit/41ace349acc39e0132a0da8498005b8680b5ed1d), and unless I'm doing something really wrong here it's slower by quite the margin. My guess is that the scanner is slow.

```
benchmark                    old ns/op     new ns/op     delta
BenchmarkMatch-4             64.1          2959          +4516.22%
BenchmarkMatchBigLate-4      6531          87971         +1246.98%
BenchmarkMatchBigEarly-4     51.4          23634         +45880.54%
```

Also, I'm not sure if it's worth the trouble to bend of backward to get good results on the large text benchmarks? I mean, given a large enough string you're basically guaranteed a match (unless you search for cyrillic in a text with only alphanumerics or similar). I'm also not sure that long texts are a common use case for fuzzy matching. Unless you're trying to find files that fuzzy matches some text.

I did some fiddling without compromising complexity too much and got this (basically use `unicode.ToLower`):

```go
func Match(source, target string) bool {
	noop := func(r rune) rune { return r }
	return match(source, target, noop)
}

func MatchFold(source, target string) bool {
	return match(source, target, unicode.ToLower)
}

func match(source, target string, fn func(rune) rune) bool {
	lenDiff := len(target) - len(source)

	if lenDiff < 0 {
		return false
	}

	if lenDiff == 0 && source == target {
		return true
	}

Outer:
	for _, r1 := range source {
		for i, r2 := range target {
			if fn(r1) == fn(r2) {
				target = target[i+utf8.RuneLen(r2):]
				continue Outer
			}
		}
		return false
	}

	return true
}
```

Difference between current master.

```bash
benchmark                    old ns/op     new ns/op     delta
BenchmarkMatch-4             62.5          98.8          +58.08%
BenchmarkMatchBigLate-4      6677          11884         +77.98%
BenchmarkMatchBigEarly-4     49.5          67.6          +36.57%
```

Bench of the `MatchFold` function.

```
BenchmarkMatchFold-4        	10000000	       107 ns/op
BenchmarkMatchFoldBigLate-4 	  100000	     18336 ns/op
BenchmarkMatchFoldBigEarly-4	20000000	        71.6 ns/op
```

And the delta between mine and yours:

```
benchmark                        old ns/op     new ns/op     delta
BenchmarkMatch-4                 102           2959          +2800.98%
BenchmarkMatchBigLate-4          12176         87971         +622.50%
BenchmarkMatchBigEarly-4         69.7          23634         +33808.18%
BenchmarkMatchFold-4             111           3046          +2644.14%
BenchmarkMatchFoldBigLate-4      19627         143404        +630.65%
BenchmarkMatchFoldBigEarly-4     73.3          25881         +35208.32%
```
